### ISSUE TITLE
Mood board for empathy

### ISSUE THREAD

**Issue by inderpreetsingh** [inderpreetsingh/a-circle-of-joy#1]
![dawn-nature-sunset-woman](https://cloud.githubusercontent.com/assets/1131610/9772182/27ba3d04-5758-11e5-9cca-bfd02090c786.jpg)

**Comment by inderpreetsingh** [comment]
![city-man-person-skyline](https://cloud.githubusercontent.com/assets/1131610/9772184/2bb012bc-5758-11e5-8326-482db2e16330.jpg)

**Comment by inderpreetsingh** [comment]
![Uploading wVlfnlTbRtK8eGvbnBZI_VolkanOlmez_005.jpg…]()

**Comment by inderpreetsingh** [comment]
![light-sky-beach-sand](https://cloud.githubusercontent.com/assets/1131610/9772317/ef967306-5758-11e5-864e-5c56d3e32fef.jpg)

**Comment by inderpreetsingh** [comment]
![nature-fashion-person-woman](https://cloud.githubusercontent.com/assets/1131610/9772488/2bc8fe7e-575a-11e5-8075-e763099b20b7.jpg)

**Comment by inderpreetsingh** [comment]
![pexels-photo](https://cloud.githubusercontent.com/assets/1131610/9772533/712321a2-575a-11e5-82db-fc505aecb97b.jpeg)

**Comment by inderpreetsingh** [comment]
![way-fence-walkway](https://cloud.githubusercontent.com/assets/1131610/9772634/059cc00e-575b-11e5-9dcb-73602b031d1d.jpg)

**Comment by inderpreetsingh** [comment]
![branches](https://cloud.githubusercontent.com/assets/1131610/9772680/4d742610-575b-11e5-8328-8c31234ef49d.jpg)

**Comment by cuberoot** [comment]
Lisa and I like a bunch of those. The ones with the guys will be better when we do the men's site.
